# Generated by Django 5.1.6 on 2025-05-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='url',
            field=models.CharField(default='127.0.0.1:8080', max_length=100),
            preserve_default=False,
        ),
    ]
