# Generated by Django 5.1.6 on 2025-04-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='under_verification',
            field=models.BooleanField(default=True),
        ),
    ]
